services:
  flask:
    build: .
    container_name: flask
    ports:
      - 5000:5000
    volumes:
      - ./src:/usr/src/burger
    depends_on:
      - neo4j
    #   - redis

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687  
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/neo4j

  # redis:
  #   image: redislabs/redismod
  #   container_name: redis
  #   ports:
  #     - 6379:6379

volumes:
  neo4j_data:
