services:
  flask:
    build: .
    container_name: flask
    ports:
      - 5000:5000
    volumes:
      - ./src:/usr/src/burger
    # depends_on:
    #   - neo4j
    #   - redis

  # neo4j:
  #   image: neo4j:latest
  #   ports:
  #     - 7474:7474
  #     - 7687:7687  

  # redis:
  #   image: redislabs/redismod
  #   container_name: redis
  #   ports:
  #     - 6379:6379
